const mongoose = require("mongoose");
const S = mongoose.Schema;

const userSchema = new S({
    name: String,
    photo: String,
});

const productSchema = new S({
  name: String,
  image: String,
  Link: String,
  GPUName: String,
  GPUVariant: String,
  Architecture: String,
  Foundry: String,
  ProcessSize: String,
  Transistors: String,
  DieSize: String,
  ReleaseDate: String,
  Availability: String,
  Generation: String,
  Predecessor: String,
  Successor: String,
  Production: String,
  LaunchPrice: String,
  BusInterface: String,
  Reviews: String,
  BaseClock: String,
  GameClock: String,
  BoostClock: String,
  MemoryClock: String,
  MemoryClock: String,
  MemorySize: String,
  MemoryType: String,
  MemoryBus: String,
  Bandwidth: String,
  ShadingUnits: String,
  TMUs: String,
  ROPs: String,
  SMCount: String,
  L1Cache: String,
  L2Cache: String,
  PixelRate: String,
  TextureRate: String,
  FP16halfperformance: String,
  FP32floatperformance: String,
  FP64doubleperformance: String,
  SlotWidth: String,
  TDP: String,
  SuggestedPSU: String,
  Outputs: String,
  PowerConnectors: String,
  DirectX: String,
  OpenGL: String,
  OpenCL: String,
  Vulkan: String,
  CUDA: String,
  ShaderModel: String,
  TensorCores: String,
  RTCores: String,
  product: [userSchema],
});

module.exports = mongoose.model("gpu", productSchema);
